### ISSUE TITLE
Perl issue in el8 container

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-docker#186]
When I run these commands:
```bash
cmssw-el8
source /cvmfs/cms.cern.ch/cmsset_default.sh
cmsenv
```

I get the following warning:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

This does not happen in e.g. the cc7 image, so something is probably missing from the el8 image.

**Comment by kpedro88** [comment]
It looks like this is fixed now. @smuzaffar can you point out which commit fixed it?

**Comment by smuzaffar** [comment]
@kpedro88 , this was fixed buy installing `glibc-langpack-en` package ( https://github.com/cms-sw/cms-docker/commit/a2a6ca43d91bca7227a46b88e1b5096c97391069 )
