### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-docker#187]
The README links to https://github.com/cms-sw/cms-docker/blob/master/jenkins, which no longer exists in the repo. It also refers to `*EXECUTE_BUILD.sh` files, but there are very few of these in the repo. These parts should be removed or updated for the latest practices.

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cms-docker/commit/5fee17e74bd5db17b93d22303adf843e31161999
