### ISSUE TITLE
For non-linux platforms

### ISSUE THREAD

**Issue by adavidzh** [cms-sw/cms-docker#2]
There is [boot2docker](http://boot2docker.io/) for Mac and Windows.
Unfortunately I was not successful with the recipe from [here](https://github.com/cms-sw/cms-sw.github.io/blob/master/docker.md) because of a `503` from `cmsdocker.cern.ch`.

**Comment by adavidzh** [comment]
Just tried again, and it's out
```
$ curl cmsdocker.cern.ch/builder-slc6_amd64_gcc481
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```

**Comment by ktf** [comment]
I moved all the images to docker hub, so that we do not have to support 
our own docker repo for now. In principle cmsdocker.cern.ch is not used 
anymore. What are you trying to do?

**Comment by adavidzh** [comment]
I was following the instructions in https://github.com/cms-sw/cms-sw.github.io/blob/master/docker.md
(Thanks for following up!)

**Comment by ktf** [comment]
Try this:

http://ktf.github.io/2015/03/cmssw-docker/

for the moment. I'll try to update the recipes in cms-sw.github.io.

-- 
Ciao,
Giulio

**Comment by adavidzh** [comment]
Ok. I got it working, but my use-case is not automation. Thanks.
