### ISSUE TITLE
All yum commands should end with " && yum clean all"

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cms-docker#28]
I checked on one of the slc-install images and this reduces the intermediate image by about 130 MB by not storing the downloaded RPM files in some image

**Comment by davidlt** [comment]
+1, this should be always the last line in _Dockerfile_.

**Comment by ericvaandering** [comment]
No, on *each* RUN line that does yum. If it's the last line of the docker file, it only makes an intermediate image that deletes all the stuff that the previous intermediate images added.

**Comment by davidlt** [comment]
Well, true if you count the layers. In your local machine you can squash them. But, yes we should attempt keeping the layers minimal. I looked our Dockerfiles and it's a mix story. Sometimes we have `yum clean all`, sometimes we don't.

Is there currently a need to build a very minimalistic image in terms of size? There are probably more stuff we could dump as it would not be needed for running grid jobs.

**Comment by ericvaandering** [comment]
No, just good practice. Reduces storage, downloads, etc.

**Comment by smuzaffar** [comment]
Thanks @ericvaandering for the suggestion, yes it make sense. 
@iahmad-khan , we should update the docker files when next time we build an image.
