### ISSUE TITLE
Adding `vim` to containers

### ISSUE THREAD

**Issue by tvami** [cms-sw/cms-docker#322]
Can you please add `vim` to the cmssw-el8 container? 

I know that `vi` is there already but vim should be small and also pretty basic. Thanks!

**Comment by aandvalenzuela** [comment]
type el8

**Comment by smuzaffar** [comment]
type cc7

Looks like vim and vi are already available in el8 and el9. `vim` is missing for `cc7` ( or `el7`) container

**Comment by aandvalenzuela** [comment]
Added in https://github.com/cms-sw/cms-docker/pull/323
