### ISSUE TITLE
A method to make docker images smaller

### ISSUE THREAD

**Issue by gartung** [cms-sw/cms-docker#33]
Docker does not free up space from deleted files. The ~5GB of rpms downloaded for a release are still counted in the image space usage even after removal. I was able to create a much smaller image this way:
docker run -it -v /tmp:/build ...
Setup as usual in /opt/cms

mv /opt/cms/slc7_amd64_gcc700/var/cmspkg /build
ln -s /opt/cms/slc7_amd64_gcc700/var    /build/cmspkg

Run cmspkg install as usual.

After install 

rm /opt/cms/slc7_amd64_gcc700/var/cmspkg
cp -rpv /build/cmspkg /opt/cms/slc7_amd64_gcc700/var

**Comment by Dr15Jones** [comment]
assign core
